name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      commit_key:
        description: 'Commit key or branch name to checkout'
        required: true
        default: 'master'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        echo "Hello ${{ github.event.inputs.commit_key }}!"
        git checkout ${{ github.event.inputs.commit_key }}
        cat README.md
