name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      commit_key:
        description: 'Commit key or branch name to checkout'
        required: true
        default: 'master'

jobs:
  print_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
      with:
        ref: 7d004c7b653f35b32543780be3ce7809a324c558

    - run: cat README.md
