name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      commit_key:
        description: 'Commit key or branch name to checkout'
        required: true
        default: 'master'

jobs:
  print_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "${{ github.event.inputs.logLevel }}"

    - run: | 
        echo "commit key: ${{ github.event.inputs.logLevel }}"
        cat README.md
